export const assets = {
  home: {
    background: "/images/home/bg-city-eclipse-main.png",
    crest: "/images/home/crest-main.png",
  },

  icons: {
    alchemyFlask: "/assets/icons/icon-alchemy-flask.png",
    bioVial: "/assets/icons/icon-bio-vial.png",
    bloodDagger: "/assets/icons/icon-blood-dagger.png",
    bloodDaggerAlt: "/assets/icons/icon-blood-dagger-alt.png",
    blueCore: "/assets/icons/icon-blue-core.png",
    emberCloak: "/assets/icons/icon-ember-cloak.png",
    emberCoreDevice: "/assets/icons/icon-ember-core-device.png",
    emberSlash: "/assets/icons/icon-ember-slash.png",
    emberTrident: "/assets/icons/icon-ember-trident.png",
    flameMace: "/assets/icons/icon-flame-mace.png",
    flamingSkull: "/assets/icons/icon-flaming-skull.png",
    flamingSkullAlt: "/assets/icons/icon-flaming-skull-alt.png",
    frostBlade: "/assets/icons/icon-frost-blade.png",
    frostCrystal: "/assets/icons/icon-frost-crystal.png",
    frostCrystalAlt: "/assets/icons/icon-frost-crystal-alt.png",
    frostGauntlet: "/assets/icons/icon-frost-gauntlet.png",
    frostHelm: "/assets/icons/icon-frost-helm.png",
    frostHelmAlt: "/assets/icons/icon-frost-helm-alt.png",
    frostSkull: "/assets/icons/icon-frost-skull.png",
    hornedSkull: "/assets/icons/icon-horned-skull.png",
    hornedSkullAlt: "/assets/icons/icon-horned-skull-alt.png",
    moltenSkull: "/assets/icons/icon-molten-skull.png",
    moltenSkullAlt: "/assets/icons/icon-molten-skull-alt.png",
    plagueRifle: "/assets/icons/icon-plague-rifle.png",
    radiantSword: "/assets/icons/icon-radiant-sword.png",
    radiantSwordAlt: "/assets/icons/icon-radiant-sword-alt.png",
    railRifle: "/assets/icons/icon-rail-rifle.png",
    runeTome: "/assets/icons/icon-rune-tome.png",
    serpentCoil: "/assets/icons/icon-serpent-coil.png",
    serpentCoilAlt: "/assets/icons/icon-serpent-coil-alt.png",
    shatteredHelmAlt: "/assets/icons/icon-shattered-helm-alt.png",
    shatteredPlate: "/assets/icons/icon-shattered-plate.png",
    shatteredSkull: "/assets/icons/icon-shattered-skull.png",
    skullHelm: "/assets/icons/icon-skull-helm.png",
    thornHeart: "/assets/icons/icon-thorn-heart.png",
    thornHeartAlt: "/assets/icons/icon-thorn-heart-alt.png",
    voidChest: "/assets/icons/icon-void-chest.png",
    voidCluster: "/assets/icons/icon-void-cluster.png",
    voidMask: "/assets/icons/icon-void-mask.png",
    voidOrb: "/assets/icons/icon-void-orb.png",
    wardShield: "/assets/icons/icon-ward-shield.png",
    wardShieldAlt: "/assets/icons/icon-ward-shield-alt.png",
    wingedHourglass: "/assets/icons/icon-winged-hourglass.png",
    wingedHourglassAlt: "/assets/icons/icon-winged-hourglass-alt.png",
  },

  creatures: {
    armoredCrawler: "/assets/creatures/creature-armored-crawler.png",
    batLurker: "/assets/creatures/creature-bat-lurker.png",
    emberBrute: "/assets/creatures/creature-ember-brute.png",
    emberWolf: "/assets/creatures/creature-ember-wolf.png",
    frostWolf: "/assets/creatures/creature-frost-wolf.png",
    infernalScorpion: "/assets/creatures/creature-infernal-scorpion.png",
    infernalScorpionElite:
      "/assets/creatures/creature-infernal-scorpion-elite.png",
    ironBrute: "/assets/creatures/creature-iron-brute.png",
    mechSpider: "/assets/creatures/creature-mech-spider.png",
    plagueDrake: "/assets/creatures/creature-plague-drake.png",
    plagueToad: "/assets/creatures/creature-plague-toad.png",
    shadowWolf: "/assets/creatures/creature-shadow-wolf.png",
    voidSpider: "/assets/creatures/creature-void-spider.png",
  },

  bosses: {
    boneHydra: "/assets/bosses/boss-bone-hydra.png",
    emberSuccubus: "/assets/bosses/boss-ember-succubus.png",
    emberWarlord: "/assets/bosses/boss-ember-warlord.png",
    frostReaperKing: "/assets/bosses/boss-frost-reaper-king.png",
    frostRevenant: "/assets/bosses/boss-frost-revenant.png",
    frostSerpent: "/assets/bosses/boss-frost-serpent.png",
    frostSerpentSovereign:
      "/assets/bosses/boss-frost-serpent-sovereign.png",
    infernalDreadlord: "/assets/bosses/boss-infernal-dreadlord.png",
    infernalThroneQueen: "/assets/bosses/boss-infernal-throne-queen.png",
    magmaBurrower: "/assets/bosses/boss-magma-burrower.png",
    obsidianThroneLord: "/assets/bosses/boss-obsidian-throne-lord.png",
    pestilentIdol: "/assets/bosses/boss-pestilent-idol.png",
    plagueTitan: "/assets/bosses/boss-plague-titan.png",
    rotToad: "/assets/bosses/boss-rot-toad.png",
    spectralKnight: "/assets/bosses/boss-spectral-knight.png",
    voidGateMatron: "/assets/bosses/boss-void-gate-matron.png",
    voidHydra: "/assets/bosses/boss-void-hydra.png",
    voidMaw: "/assets/bosses/boss-void-maw.png",
    voidMawAlpha: "/assets/bosses/boss-void-maw-alpha.png",
  },

  factions: {
    bio: "/icons/factions/faction-bio-core.png",
    mecha: "/icons/factions/faction-mecha-core.png",
    pure: "/icons/factions/faction-spirit-core.png",
  },

  ui: {
    alert: "/icons/ui/ui-alert.png",
    profile: "/icons/ui/ui-profile.png",
    settings: "/icons/ui/ui-settings.png",
  },

  resources: {
    credits: "/icons/resources/resource-credits.png",
    voidCrystals: "/icons/resources/resource-void-crystals.png",
    bioEssence: "/icons/resources/resource-bio-essence.png",
  },
} as const;
