export const assets = {
  home: {
    background: "/images/home/bg-city-eclipse-main.png",
    crest: "/images/home/crest-main.png",
  },

  icons: {
    alchemyFlask: "/assets/icons/icon-alchemy-flask.png",
    bioVial: "/assets/icons/icon-bio-vial.png",
    bloodDagger: "/assets/icons/icon-blood-dagger.png",
    bloodDaggerAlt: "/assets/icons/icon-blood-dagger-alt.png",
    blueCore: "/assets/icons/icon-blue-core.png",
    emberCloak: "/assets/icons/icon-ember-cloak.png",
    emberCoreDevice: "/assets/icons/icon-ember-core-device.png",
    emberSlash: "/assets/icons/icon-ember-slash.png",
    emberTrident: "/assets/icons/icon-ember-trident.png",
    flameMace: "/assets/icons/icon-flame-mace.png",
    flamingSkull: "/assets/icons/icon-flaming-skull.png",
    flamingSkullAlt: "/assets/icons/icon-flaming-skull-alt.png",
    frostBlade: "/assets/icons/icon-frost-blade.png",
    frostCrystal: "/assets/icons/icon-frost-crystal.png",
    frostCrystalAlt: "/assets/icons/icon-frost-crystal-alt.png",
    frostGauntlet: "/assets/icons/icon-frost-gauntlet.png",
    frostHelm: "/assets/icons/icon-frost-helm.png",
    frostHelmAlt: "/assets/icons/icon-frost-helm-alt.png",
    frostSkull: "/assets/icons/icon-frost-skull.png",
    hornedSkull: "/assets/icons/icon-horned-skull.png",
    hornedSkullAlt: "/assets/icons/icon-horned-skull-alt.png",
    moltenSkull: "/assets/icons/icon-molten-skull.png",
    moltenSkullAlt: "/assets/icons/icon-molten-skull-alt.png",
    plagueRifle: "/assets/icons/icon-plague-rifle.png",
    radiantSword: "/assets/icons/icon-radiant-sword.png",
    radiantSwordAlt: "/assets/icons/icon-radiant-sword-alt.png",
    railRifle: "/assets/icons/icon-rail-rifle.png",
    runeTome: "/assets/icons/icon-rune-tome.png",
    serpentCoil: "/assets/icons/icon-serpent-coil.png",
    serpentCoilAlt: "/assets/icons/icon-serpent-coil-alt.png",
    shatteredHelmAlt: "/assets/icons/icon-shattered-helm-alt.png",
    shatteredPlate: "/assets/icons/icon-shattered-plate.png",
    shatteredSkull: "/assets/icons/icon-shattered-skull.png",
    skullHelm: "/assets/icons/icon-skull-helm.png",
    thornHeart: "/assets/icons/icon-thorn-heart.png",
    thornHeartAlt: "/assets/icons/icon-thorn-heart-alt.png",
    voidChest: "/assets/icons/icon-void-chest.png",
    voidCluster: "/assets/icons/icon-void-cluster.png",
    voidMask: "/assets/icons/icon-void-mask.png",
    voidOrb: "/assets/icons/icon-void-orb.png",
    wardShield: "/assets/icons/icon-ward-shield.png",
    wardShieldAlt: "/assets/icons/icon-ward-shield-alt.png",
    wingedHourglass: "/assets/icons/icon-winged-hourglass.png",
    wingedHourglassAlt: "/assets/icons/icon-winged-hourglass-alt.png",

    generated: {
      bioMaterials: {
        thornHeart: "/assets/icons/icon-bio-material-thorn-heart.png",
        vineCluster: "/assets/icons/icon-bio-material-vine-cluster.png",
        voidShard: "/assets/icons/icon-bio-material-void-shard.png",
        sporeVial: "/assets/icons/icon-bio-material-spore-vial.png",
        seedCanister: "/assets/icons/icon-bio-material-seed-canister.png",
        emberNodule: "/assets/icons/icon-bio-material-ember-nodule.png",
        brainMass: "/assets/icons/icon-bio-material-brain-mass.png",
        sporePods: "/assets/icons/icon-bio-material-spore-pods.png",
        rootSkein: "/assets/icons/icon-bio-material-root-skein.png",
        mossClump: "/assets/icons/icon-bio-material-moss-clump.png",
        bulbCore: "/assets/icons/icon-bio-material-bulb-core.png",
        tendrilMass: "/assets/icons/icon-bio-material-tendril-mass.png",
        rotCluster: "/assets/icons/icon-bio-material-rot-cluster.png",
        nerveSpark: "/assets/icons/icon-bio-material-nerve-spark.png",
        carapaceRelic: "/assets/icons/icon-bio-material-carapace-relic.png",
        bloomHeart: "/assets/icons/icon-bio-material-bloom-heart.png",
      },
      pureMaterials: {
        emberFragment: "/assets/icons/icon-pure-material-ember-fragment.png",
        magmaOrb: "/assets/icons/icon-pure-material-magma-orb.png",
        emberCrystal: "/assets/icons/icon-pure-material-ember-crystal.png",
        flameRibbon: "/assets/icons/icon-pure-material-flame-ribbon.png",
        emberRune: "/assets/icons/icon-pure-material-ember-rune.png",
        amethystShard: "/assets/icons/icon-pure-material-amethyst-shard.png",
        cinderSkull: "/assets/icons/icon-pure-material-cinder-skull.png",
        sunSeal: "/assets/icons/icon-pure-material-sun-seal.png",
        solarOrb: "/assets/icons/icon-pure-material-solar-orb.png",
        heatVial: "/assets/icons/icon-pure-material-heat-vial.png",
        infernoSkull: "/assets/icons/icon-pure-material-inferno-skull.png",
        voidOrb: "/assets/icons/icon-pure-material-void-orb.png",
        prismFrame: "/assets/icons/icon-pure-material-prism-frame.png",
        starlitVial: "/assets/icons/icon-pure-material-starlit-vial.png",
        scorchedShard: "/assets/icons/icon-pure-material-scorched-shard.png",
        solarCrystal: "/assets/icons/icon-pure-material-solar-crystal.png",
      },
      mechaMaterials: {
        crystalCluster: "/assets/icons/icon-mecha-material-crystal-cluster.png",
        alloyShard: "/assets/icons/icon-mecha-material-alloy-shard.png",
        energyCore: "/assets/icons/icon-mecha-material-energy-core.png",
        circuitSlab: "/assets/icons/icon-mecha-material-circuit-slab.png",
        crystalSpire: "/assets/icons/icon-mecha-material-crystal-spire.png",
        powerCell: "/assets/icons/icon-mecha-material-power-cell.png",
        dataCube: "/assets/icons/icon-mecha-material-data-cube.png",
        alloySpike: "/assets/icons/icon-mecha-material-alloy-spike.png",
        capacitorTube: "/assets/icons/icon-mecha-material-capacitor-tube.png",
        arcReactor: "/assets/icons/icon-mecha-material-arc-reactor.png",
        batteryPack: "/assets/icons/icon-mecha-material-battery-pack.png",
        cryoBlock: "/assets/icons/icon-mecha-material-cryo-block.png",
        prismSpike: "/assets/icons/icon-mecha-material-prism-spike.png",
        coilRing: "/assets/icons/icon-mecha-material-coil-ring.png",
        injectorSpike: "/assets/icons/icon-mecha-material-injector-spike.png",
        hexCore: "/assets/icons/icon-mecha-material-hex-core.png",
      },
      bioConsumables: {
        injector: "/assets/icons/icon-bio-consumable-injector.png",
        leafVial: "/assets/icons/icon-bio-consumable-leaf-vial.png",
        canister: "/assets/icons/icon-bio-consumable-canister.png",
        phial: "/assets/icons/icon-bio-consumable-phial.png",
      },
      bioMechaConsumables: {
        orbCanister: "/assets/icons/icon-bio-mecha-consumable-orb-canister.png",
        lanternVial: "/assets/icons/icon-bio-mecha-consumable-lantern-vial.png",
        wiredPhial: "/assets/icons/icon-bio-mecha-consumable-wired-phial.png",
        reactorOrb: "/assets/icons/icon-bio-mecha-consumable-reactor-orb.png",
      },
      bioPureConsumables: {
        flameOrb: "/assets/icons/icon-bio-pure-consumable-flame-orb.png",
        flameLantern: "/assets/icons/icon-bio-pure-consumable-flame-lantern.png",
        flamePhial: "/assets/icons/icon-bio-pure-consumable-flame-phial.png",
        cinderOrb: "/assets/icons/icon-bio-pure-consumable-cinder-orb.png",
      },
      mechaConsumables: {
        cellCanister: "/assets/icons/icon-mecha-consumable-cell-canister.png",
        batteryPack: "/assets/icons/icon-mecha-consumable-battery-pack.png",
        powerCanister: "/assets/icons/icon-mecha-consumable-power-canister.png",
        injectorVial: "/assets/icons/icon-mecha-consumable-injector-vial.png",
      },
      mechaPureConsumables: {
        reactorOrb: "/assets/icons/icon-mecha-pure-consumable-reactor-orb.png",
        furnaceLantern:
          "/assets/icons/icon-mecha-pure-consumable-furnace-lantern.png",
        furnaceCanister:
          "/assets/icons/icon-mecha-pure-consumable-furnace-canister.png",
        furnaceCore: "/assets/icons/icon-mecha-pure-consumable-furnace-core.png",
      },
      pureConsumables: {
        crystalOrb: "/assets/icons/icon-pure-consumable-crystal-orb.png",
        emberFlask: "/assets/icons/icon-pure-consumable-ember-flask.png",
        emberTube: "/assets/icons/icon-pure-consumable-ember-tube.png",
        voidOrb: "/assets/icons/icon-pure-consumable-void-orb.png",
      },
      statusEffects: {
        poisoned: "/assets/icons/icon-status-poisoned.png",
        burning: "/assets/icons/icon-status-burning.png",
        shocked: "/assets/icons/icon-status-shocked.png",
        corrupted: "/assets/icons/icon-status-corrupted.png",
        exhausted: "/assets/icons/icon-status-exhausted.png",
        stabilized: "/assets/icons/icon-status-stabilized.png",
        enraged: "/assets/icons/icon-status-enraged.png",
        mutated: "/assets/icons/icon-status-mutated.png",
        infected: "/assets/icons/icon-status-infected.png",
        soulBurn: "/assets/icons/icon-status-soul-burn.png",
        shielded: "/assets/icons/icon-status-shielded.png",
        regenerating: "/assets/icons/icon-status-regenerating.png",
      },
    },
  },

  creatures: {
    armoredCrawler: "/assets/creatures/creature-armored-crawler.png",
    batLurker: "/assets/creatures/creature-bat-lurker.png",
    emberBrute: "/assets/creatures/creature-ember-brute.png",
    emberWolf: "/assets/creatures/creature-ember-wolf.png",
    frostWolf: "/assets/creatures/creature-frost-wolf.png",
    infernalScorpion: "/assets/creatures/creature-infernal-scorpion.png",
    infernalScorpionElite:
      "/assets/creatures/creature-infernal-scorpion-elite.png",
    ironBrute: "/assets/creatures/creature-iron-brute.png",
    mechSpider: "/assets/creatures/creature-mech-spider.png",
    plagueDrake: "/assets/creatures/creature-plague-drake.png",
    plagueToad: "/assets/creatures/creature-plague-toad.png",
    shadowWolf: "/assets/creatures/creature-shadow-wolf.png",
    voidSpider: "/assets/creatures/creature-void-spider.png",
  },

  bosses: {
    boneHydra: "/assets/bosses/boss-bone-hydra.png",
    emberSuccubus: "/assets/bosses/boss-ember-succubus.png",
    emberWarlord: "/assets/bosses/boss-ember-warlord.png",
    frostReaperKing: "/assets/bosses/boss-frost-reaper-king.png",
    frostRevenant: "/assets/bosses/boss-frost-revenant.png",
    frostSerpent: "/assets/bosses/boss-frost-serpent.png",
    frostSerpentSovereign:
      "/assets/bosses/boss-frost-serpent-sovereign.png",
    infernalDreadlord: "/assets/bosses/boss-infernal-dreadlord.png",
    infernalThroneQueen: "/assets/bosses/boss-infernal-throne-queen.png",
    magmaBurrower: "/assets/bosses/boss-magma-burrower.png",
    obsidianThroneLord: "/assets/bosses/boss-obsidian-throne-lord.png",
    pestilentIdol: "/assets/bosses/boss-pestilent-idol.png",
    plagueTitan: "/assets/bosses/boss-plague-titan.png",
    rotToad: "/assets/bosses/boss-rot-toad.png",
    spectralKnight: "/assets/bosses/boss-spectral-knight.png",
    voidGateMatron: "/assets/bosses/boss-void-gate-matron.png",
    voidHydra: "/assets/bosses/boss-void-hydra.png",
    voidMaw: "/assets/bosses/boss-void-maw.png",
    voidMawAlpha: "/assets/bosses/boss-void-maw-alpha.png",
  },

  factions: {
    bio: "/icons/factions/faction-bio-core.png",
    mecha: "/icons/factions/faction-mecha-core.png",
    pure: "/icons/factions/faction-spirit-core.png",
  },

  ui: {
    alert: "/icons/ui/ui-alert.png",
    profile: "/icons/ui/ui-profile.png",
    settings: "/icons/ui/ui-settings.png",
  },

  resources: {
    credits: "/icons/resources/resource-credits.png",
    voidCrystals: "/icons/resources/resource-void-crystals.png",
    bioEssence: "/icons/resources/resource-bio-essence.png",
  },
} as const;
