export const EXPLORATION_FIELD_RATION_COST = 1;
export const MISSION_FIELD_RATION_COST = 1;

export const RATION_SYNTHESIS_CREDIT_COST = 15;
export const RATION_SYNTHESIS_BIO_SAMPLE_COST = 2;
export const RATION_SYNTHESIS_OUTPUT = 3;
